// ===========================================================================
// THE SKILL ICONS — how the three skill buttons' pictures are MADE.
//
// The user's brief, and it is a RECIPE rather than a request for a drawing:
//
//   *"can u add icons for skill 1 and 2 and 3 ill tell u how to make the icons  make the player do
//   the skill and in the middle of that skill the part where he hits the enemy pause it there and
//   make the farther limbs from the camera gray and make the player white and add outline of course
//   now take the player and make it into an icon only the player and put it in the skill instead
//   next to number like this (SKILL ICON)¹ and the little number is the skill number"*
//
// So the icons are not drawn and not generated by a model: they are SCREENSHOTS OF THE REAL RIG, at
// the real contact frame of the real move, taken through the real shader. Which means they cannot
// drift from the game — if a pose is retuned, the fix is to run `GAME.bakeIcons()` again.
//
// HOW A FRAME BECOMES AN ICON, in the order the brief gives it:
//
//   1. THE SKILL IS PLAYED. A body is parked the right distance in front of the player (see
//      `SKILL_ICON_CFG`), the move is thrown, and the loop is stepped until the move's OWN hit flag
//      goes up (`kneeHit` / `scissorHitDone` / `capoHit`) — the same flags the fight reads, so the
//      icon is the frame the game counts as the contact and not a frame number that drifted.
//   2. ONLY THE PLAYER. His rig is reparented into a throwaway scene: no world, no sky, no shadow,
//      no dummy, no FX. (The dummy is why the frame is a hit frame, not part of the picture — the
//      brief says *"only the player"*.)
//   3. THE CAMERA IS FITTED TO THE BODY, which takes two passes and is the one part of this that is
//      not obvious. The pose is framed first from a sphere-fit standoff and photographed once, cheap,
//      at the probe size; that frame is only read for WHERE the body lands in pixels; then the camera
//      is swung to look at the middle of it and pulled in until the body fills a fixed fraction of the
//      buffer, and THAT frame is the icon. It matters because the sphere fit frames a ball around the
//      pose's bounding box and a pose is not a ball: the first draft photographed a body filling half
//      the buffer, and the crop then magnified it — and the ink with it — by 1.7.
//   4. WHITE IN FRONT, GRAY BEHIND. `shared.uFlat` is the renderer's own cut-out mode (see the note
//      on it in ps1.js): every body material draws as pure white washed toward `0.42` gray by its
//      distance from the camera, with no lighting, no fog and no texture. The depth band is the
//      pose's own depth, read in CAMERA space, and the curve inside it is a plateau — the front
//      third white, then the gray coming in to full at the back — because a plain linear mix left
//      the icons reading as one flat gray mass.
//   5. THE OUTLINE. The ink shells are ordinary meshes on the rig, so they are simply made visible
//      and drawn; only the ink WIDTH is re-authored, in buffer pixels, for the small buffer.
//   6. THE CUT-OUT IS TAKEN. The pass renders into its own render target over a pure magenta clear
//      and the pixels are read back — `readRenderTargetPixels`, so nothing depends on the tab being
//      visible or on `preserveDrawingBuffer`. The magenta is the key: the body is white/gray/black,
//      so a saturated colour that appears nowhere in the picture is a safe mask, and the silhouette
//      is hard-edged (no MSAA, `uSnap` off), so there is no fringe to clean up.
//   7. IT IS CROPPED TO THE BODY and fitted to the icon box with a margin — the brief's *"only the
//      player"* done a second time, this time on the pixels. Because step 3 already filled the
//      buffer, the fit is about 0.88 and so the ink keeps the thickness it was authored at.
//
// The result is a PNG with an ALPHA channel, which is why the buttons can sit it on the same dark
// plate as their labels (see `.skIcon` in index.html).
//
// RUNNING IT: from the editor, `GAME.bakeIcons({only:n})` returns `{n: "data:image/png;base64,…", n:
// {…diag}}`; the built assets live in `src/hud/skill1.png` … `skill3.png`, and the baker exists in the
// shipped source only as the recipe that rebuilds them (they were baked at `{size:160, icon:144}`, the
// 144 being the icon's real pixel size — the buttons draw it at 34 CSS px, so it is crisp on a retina
// screen). `only` is per SKILL and `dirA`/`elev`/`ink`/`ramp`/`fill`/`flat` override the camera and the
// look, which is how the angles were chosen (eight-angle sheets per pose, judged at button size) —
// `{flat:false}` renders the same frame through the ordinary materials for looking at the staging.
// It drives the live page in manual mode, so leave the tab alone while it runs — about a second a
// skill. Re-baking writes the same filename, so the ONLY caching trap is the preview: an `<img>` that
// is already on the page will keep showing the bytes it decoded, and a hard reload may not help.
// ===========================================================================
import * as THREE from "./three.js";
import { settings, shared, setOutlineEnabled } from "./ps1.js";

const D2R = Math.PI / 180;

// The POSED bounding box of a body — and it cannot be `Box3.setFromObject`, for two reasons that
// both showed up as a body too small in the frame (the crop then magnified it, and it magnified the
// ink with it). `setFromObject` walks every child whatever its `visible` flag, so the flash hulls —
// inflated copies of the whole body, switched off during a bake — and the ink shells were being
// measured as part of the man. And a skinned mesh's geometry box is its BIND pose, which for a body
// mid-flying-knee is a standing figure: nothing like the pixels on screen. So the hulls are skipped
// by hand and each skinned mesh is measured through its own `computeBoundingBox`, which applies the
// bones and hands back the box of the pose actually being drawn.
function bodyBox(root) {
  const box = new THREE.Box3();
  const one = new THREE.Box3();
  root.traverse((o) => {
    const ud = o.userData || {};
    // `o.visible` is checked because the rig carries a hidden 2.2-unit box mesh (a leftover
    // collider, by the look of it) that is never drawn and yet was the single biggest thing in the
    // frame: it alone was most of the box, which is why the body came out a third of the buffer.
    if (!o.visible || ud.isFlash || ud.isOutline || !o.geometry) return;
    if (o.isSkinnedMesh && o.computeBoundingBox) {
      o.computeBoundingBox();
      if (!o.boundingBox) return;
      one.copy(o.boundingBox);
    } else {
      if (!o.geometry.boundingBox) o.geometry.computeBoundingBox();
      one.copy(o.geometry.boundingBox);
    }
    one.applyMatrix4(o.matrixWorld);
    box.union(one);
  });
  return box;
}

// One entry per skill button. `dist` is how far the player stands from the dummy when the move is
// thrown — set from the move's OWN reach, or (the knee) from how long a run-up is wanted. `dirA` is
// the camera's direction FROM the body, written relative to the line the player faces (`aim`), which
// is what makes one number work whatever way the pair happen to be pointing in the world.
//
// The angles were chosen by eye, off eight-angle sheets of each pose (see "running it" below), and
// the whole job of the sheets was legibility at the size these are actually seen: about 36 pixels.
// What that rules out is foreshortening. A strike thrown at the camera is one lump at 36 pixels
// whatever it does, so each move is shot as close to square-on to its own direction of travel as the
// pose allows — the knee from his right, the scissor and the launch from the side — and the two
// moves whose limb swings around the body rather than away from it want the camera a little above
// the waist, or the swinging leg points at the lens and vanishes.
// WHICH BEAT OF SKILL 3's CARRY THE ICON IS TAKEN ON (session 186). The capoeira has four phases
// (charge / kick / recover / carry) and the icon is shot in the last one; this is how far through
// that phase the shape has to be before it counts as settled — late enough that the legs have stepped
// forward onto presented soles and the arms have opened wide, early enough that the hold has not
// started to unwind. Read off the move's OWN phase clock (see `capoPhase`/`capoBeat`), not a frame.
const CAPO_ICON_PH = 0.72;

export const SKILL_ICON_CFG = [
  {
    n: 1,
    dist: 5.2,
    fire: (pl) => pl.knee(),
    hit: (pl) => pl.kneeHit,
    rewind: 1,
    dirA: (aim) => aim - 90 * D2R,
    elev: 0.02,
  },
  {
    n: 2,
    dist: 2.0,
    fire: (pl) => pl.scissor(),
    hit: (pl) => pl.scissorHitDone,
    dirA: (aim) => aim - 45 * D2R,
    elev: 0.35,
  },
  {
    n: 3,
    dist: 2.1,
    fire: (pl) => pl.capoeira(),
    // THE FRAME IS THE CARRY, NOT THE CONTACT (session 186 — the user's *"make skill 3 icon the new
    // animation"*). The contact is a pair of legs snapping up about the hips with the trunk whipped
    // clean over; it was MEASURED as a plain vertical blob from every angle tried (square on, both
    // sides, 3/4s, with and without an arm spread) because the current height and arch put every limb
    // on top of the body — which is why `src/hud/skill3.png` had been left wearing an older pose
    // rather than degraded to the blob. The fix the old note named is this one: shoot the HOLD. In the
    // CARRY the body has righted itself over the hips, the legs have stepped forward with the soles
    // presented and the arms have opened WIDE, which is the one beat of this move that has a
    // silhouette. So the frame is the point in phase 3 where that shape has settled (`CAPO_ICON_PH`).
    hit: (pl) => pl.capoPhase() === 3 && pl.capoBeat().ph >= CAPO_ICON_PH,
    // SQUARE FROM BEHIND, which is the view the player already has of this move (the chase camera is
    // behind him) and the one whose silhouette survived the test at the button's own 34 px — both arms
    // read straight out to the sides with the stepped legs below them. Every angle ACROSS the pose
    // (3/4s and sides) foreshortened the body into a diagonal mass; the front was legible too but the
    // arms dropped out of the horizontal and the whole shape went wider and lower.
    dirA: (aim) => aim - 180 * D2R,
    elev: 0.12,
  },
];

// Where the body sits in a buffer of the cut-out: the bounding box of every pixel that is NOT the
// magenta key, in canvas coordinates (row 0 at the top — WebGL hands the rows back bottom-up). Null
// if the frame came back empty. This is the measurement the camera fit is built on.
function pixelBounds(buf, res) {
  let minX = res;
  let minY = res;
  let maxX = -1;
  let maxY = -1;
  for (let y = 0; y < res; y++) {
    for (let x = 0; x < res; x++) {
      const si = ((res - 1 - y) * res + x) * 4;
      if (buf[si] > 190 && buf[si + 1] < 70 && buf[si + 2] > 190) continue;
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
  }
  if (maxX < 0) return null;
  return { minX, minY, maxX, maxY, w: maxX - minX + 1, h: maxY - minY + 1 };
}

// One icon. `g` is the game handle (`window.GAME`).
export async function bakeSkillIcons(g, opts = {}) {
  const size = opts.size || 144;     // the render buffer (square)
  const icon = opts.icon || 128;     // the finished icon (square)
  const only = opts.only ? [].concat(opts.only) : null;
  const dt = 1 / 60;
  const wait = (ms) => new Promise((r) => setTimeout(r, ms));
  if (!g.hasStarted) g.start();
  // `keepOverlay` is the editor's own auto-bake (see `autoBakeIconsForEditor` in main.js): that bake
  // runs BEHIND the title card, so it may not dismiss it. Left off, `setManual(true)` hides the
  // overlay exactly as it always has (a `GAME.bakeIcons()` from the console still wants a clear screen).
  g.setManual(true, opts.keepOverlay ? { keepOverlay: true } : undefined);
  // The rigs are built in the background, one per frame (see `Enemies.pump`), so give the queue a
  // chance to drain before the first bake rather than reporting "no enemy".
  for (let i = 0; i < 90 && (!g.player.charMesh || !g.enemies.list.some((e) => e.built)); i++) {
    g.step(dt, {});
    await wait(30);
  }
  const out = {};
  for (const cfg of SKILL_ICON_CFG) {
    if (only && only.indexOf(cfg.n) < 0) continue;    // A FRESH DUMMY PER ICON, SPAWNED FROM HOME. A body that has just been kneed through, scissored
    // off its feet and launched into the sky is still lying where the last shot left it — and worse,
    // it is still in whatever reaction state that was, so its head is not where a standing body's
    // head is and the next move whiffs on it. The first draft reused one dummy and the second and
    // third icons came out empty; the second draft spawned the new one wherever the last shot had
    // left the PLAYER, which is how the dummy ended up on top of a wall. So: the player is put back
    // at the spawn (flat, open camp — the training grounds) and the dummy is asked for from there,
    // which lands it on the same patch of deck every time.
    g.player.respawn();
    // The camera is squared to the world first: `Enemies.spawn` lays the dummy out along the CAMERA's
    // line, so leaving the rig wherever the last shot pointed it is what made the same skill land one
    // run and whiff the next (the pair came down on a different patch of ground each time).
    g.rig.yaw = 0;
    for (let i = 0; i < 14; i++) g.step(dt, {});
    const dummy = await freshDummy(g, wait, dt);
    if (!dummy) { out[cfg.n] = { error: "no fresh dummy" }; continue; }
    out[cfg.n] = await bakeOne(g, cfg, {
      size, icon, dummy, flat: opts.flat, margin: opts.margin,
      dirA: opts.dirA, elev: opts.elev, fov: opts.fov, ink: opts.ink, ramp: opts.ramp,
    });
  }
  // Manual mode is how a bake drives the simulation, and the loop returns before it steps anything
  // while it is on (see `if (manual) return;` in main.js) — so leaving it on would hand the page back
  // frozen, which looks exactly like a crash. It goes off again at the end of every batch.
  g.setManual(false);
  return out;
}

// ---------------------------------------------------------------------------
// PUTTING THE ICONS ON THE HUD — AND DOING IT BY ITSELF (session 186).
//
// The user's brief: *"make skill 3 icon the new animation and make the skills in the feature
// automatically do that"*. Two halves: skill 3's icon is shot from the move's own CARRY now (see
// `SKILL_ICON_CFG`), and the icons are no longer something a later session has to remember to
// re-bake — they BAKE THEMSELVES off the rig while the game is being worked on.
//
// WHERE THE FALLBACK LIVES. The build ships the PNGs in `src/hud/`, so the published game pays
// nothing for this: no bake, no wait, no extra draw, just the three `<img>`s it always had. The
// self-bake is gated on `window.generatorIsUnsaved` (see the call in main.js), i.e. it runs ONLY in
// the editor preview — which is exactly where a pose that has just been retuned makes the shipped
// PNGs stale. A saved generator keeps its baked icons; an unsaved one rebuilds them from whatever the
// rig is doing this minute. That is the whole trick, and it is why nothing here touches the shipping
// path. `window.__noAutoIcons = true` (a `page_refresh` preamble, or the console) stands it down.
const SKILL_BUTTON_IDS = { 1: "btnWhirl", 2: "btnScissor", 3: "btnCapo" };

// Swap the HUD's own `<img class="skIcon">` for a freshly baked set (one data-URL PNG per skill, as
// `bakeSkillIcons` returns them). A skill with no result keeps the shipped PNG it is already wearing.
export function applySkillIcons(out) {
  for (const n of Object.keys(SKILL_BUTTON_IDS)) {
    const r = out && out[n];
    if (!r || !r.url) continue;
    const btn = document.getElementById(SKILL_BUTTON_IDS[n]);
    const img = btn && btn.querySelector("img.skIcon");
    if (img) img.src = r.url;
  }
}

// Bake all three and put them on the HUD — the one call the editor's auto-bake makes. The sizes match
// the shipped assets (see the note above `bakeSkillIcons`), so an auto-baked icon is the icon a manual
// `GAME.bakeIcons()` would produce, pixel for pixel.
export async function autoBakeIcons(g, opts = {}) {
  const out = await bakeSkillIcons(g, Object.assign({ size: 160, icon: 144 }, opts));
  applySkillIcons(out);
  return out;
}

// Throw the current field away and ask for a new one. The rigs build in the background (one per
// frame — see `Enemies.pump`), so this waits for the new body to arrive.
async function freshDummy(g, wait, dt) {
  const old = g.enemies.list.splice(0, g.enemies.list.length);
  for (const o of old) {
    if (o.group && o.group.parent) o.group.parent.remove(o.group);
  }
  g.enemies.buildQueue.length = 0;
  g.enemies.spawn(g.player);
  const e = g.enemies.list[g.enemies.list.length - 1];
  for (let i = 0; i < 150 && !e.built; i++) {
    g.step(dt, {});
    await wait(25);
  }
  return e.built ? e : null;
}

// Everything under one `SKILL_ICON_CFG`, and the only function here that touches the page.
export async function bakeOne(g, cfg, o = {}) {
  const THREE_ = THREE;
  const pl = g.player;
  const dt = 1 / 60;
  const size = o.size || 144;
  const icon = o.icon || 128;
  const e = o.dummy || g.enemies.list.find((x) => x.built) || g.enemies.list[0];
  if (!e || !e.built) return { error: "no built dummy" };

  // ---- 1. THE STAGE. Both bodies are put on a clean line on the deck: the dummy's own ground is
  // the anchor (it is placed where the world guarantees floor), and the player is pulled back along
  // that line to `dist`. He is left a few frames to settle, and the dummy is stood back up, because
  // the previous skill in the same batch may have thrown it.
  pl.respawn();
  pl.setState("ground");
  // Every clock and flag the move reads is wiped first: a batch bakes all three skills out of one
  // page, and the second bake would otherwise find the first one's cooldown still running (the
  // press is refused) and its contact flag still up (the frame wait finds a hit immediately) — which
  // photographs the PREVIOUS skill. The first draft did exactly that.
  pl.kneeCd = 0;
  pl.scissorCd = 0;
  pl.capoCd = 0;
  pl.kneeHit = false;
  pl.scissorHitDone = false;
  pl.capoHit = false;
  pl.hitstop = 0;
  for (let i = 0; i < 16; i++) g.step(dt, {});
  const aim = Math.atan2(e.pos.x - pl.pos.x, e.pos.z - pl.pos.z);
  pl.pos.x = e.pos.x - Math.sin(aim) * cfg.dist;
  pl.pos.z = e.pos.z - Math.cos(aim) * cfg.dist;
  pl.vel.set(0, 0, 0);
  // Put him ON the deck rather than letting him fall to it: a drop of a couple of units takes a
  // fifth of a second and the settle below is shorter than that, which would leave the shot with a
  // body still on its way down.
  const gy = g.world.topBelow(pl.pos.x, pl.pos.z, 400, 900);
  if (isFinite(gy)) pl.pos.y = gy + g.P.HY + 0.05;
  e.hp = 100;
  e.ragdoll = false;
  e.setState("idle");
  e.place(e.pos.x, e.pos.z, aim + Math.PI);
  e.settle(true);
  const face = () => { pl.facing = aim; pl.camYaw = aim + Math.PI; g.rig.yaw = aim + Math.PI; };
  face();
  for (let i = 0; i < 16; i++) { face(); g.step(dt, {}); }

  // ---- 2. THE MOVE, played to its own contact frame.
  //
  // `cfg.rewind` is why a pose is SNAPSHOT before every step. The knee is the reason it exists: its
  // contact is what ends its leap (`kneeContact` -> `kneeToLand` on the same frame), so the very
  // frame the game counts as the hit is already drawn in the landing brace — the knee is back under
  // the body. The picture the user is asking for is the frame the knee ARRIVES, which is one step
  // earlier, so the pose from before the hit step is restored over the hit frame's. (The scissor and
  // the launch need no rewind: their contact beats are beats of a clock their poses run on, so the
  // hit frame's own pose is the strike.)
  const snapBones = () => {
    const arr = [];
    pl.charMesh.traverse((o2) => {
      arr.push(
        o2.position.x, o2.position.y, o2.position.z,
        o2.rotation.x, o2.rotation.y, o2.rotation.z,
        o2.scale.x, o2.scale.y, o2.scale.z
      );
    });
    return arr;
  };
  const putBones = (arr) => {
    let i = 0;
    pl.charMesh.traverse((o2) => {
      o2.position.set(arr[i], arr[i + 1], arr[i + 2]);
      o2.rotation.set(arr[i + 3], arr[i + 4], arr[i + 5]);
      o2.scale.set(arr[i + 6], arr[i + 7], arr[i + 8]);
      i += 9;
    });
  };
  const range0 = Math.hypot(e.pos.x - pl.pos.x, e.pos.z - pl.pos.z);
  const headV = e.headPoint ? e.headPoint(new THREE_.Vector3()) : null;
  const fired = cfg.fire(pl);
  let frames = 0;
  let held = null;
  while (!cfg.hit(pl) && frames < 300) {
    face();
    held = snapBones();
    g.step(dt, {});
    frames++;
  }
  const diag = {
    fired, frames, state: pl.state, aim: +aim.toFixed(3), range0: +range0.toFixed(2),
    // How high the dummy's head stands over the deck it is on, and how high the player's feet are
    // over his own: a pair that is not on the same, flat deck is why a move whiffs, and this is the
    // number that says so (see the staging notes above).
    headH: headV ? +(headV.y - e.pos.y).toFixed(2) : null,
    deckGap: +((pl.pos.y - g.P.HY) - e.pos.y).toFixed(2),
  };
  if (!cfg.hit(pl)) return { error: "no contact", diag };
  if (cfg.rewind && held) {
    putBones(held);
    diag.rewound = cfg.rewind;
  }
  // Where the limbs actually are at the contact, relative to his own feet. This is what the camera
  // angles were picked from: a pose's name says nothing about which way it is pointing, and the
  // launch in particular reads as a standing man from every side-on angle and is in fact a kick-up
  // (at the contact its feet are at 1.6 and 1.8, above its head) — a thing no amount of eyeballing
  // silhouettes had settled, and one number apiece did.
  diag.bones = {};
  {
    const bl = pl.charMesh.userData.bones;
    const v = new THREE_.Vector3();
    for (const k of ["hips", "head", "handL", "handR", "footL", "footR"]) {
      if (!bl || !bl[k]) continue;
      bl[k].getWorldPosition(v);
      diag.bones[k] = [+(v.x - pl.pos.x).toFixed(2), +(v.y - pl.pos.y).toFixed(2), +(v.z - pl.pos.z).toFixed(2)];
    }
  }

  // ---- 3. THE CUT-OUT. The rig goes into a scene of its own, its flash hulls are put out, and the
  // ink is forced on (the player may have OUTLINE switched off — an icon without its line is not the
  // picture that was asked for).
  const iconScene = new THREE_.Scene();
  const parent = pl.group.parent;
  const touched = [];
  pl.charMesh.traverse((o2) => {
    const ud = o2.userData || {};
    if (ud.isFlash || ud.isOutline) { touched.push([o2, o2.visible]); o2.visible = !!ud.isOutline; }
  });
  pl.charMesh.updateWorldMatrix(true, true);
  let box = bodyBox(pl.group);
  if (box.isEmpty()) box = new THREE_.Box3().setFromObject(pl.group);
  const ctr = box.getCenter(new THREE_.Vector3());
  const sph = box.getBoundingSphere(new THREE_.Sphere());
  iconScene.add(pl.group);

  const fov = o.fov || 40;
  const cam = new THREE_.PerspectiveCamera(fov, 1, 0.05, 90);
  // The camera's own angle is overridable so a batch can be swept while a skill is being framed by
  // eye (see "running it" at the top): `dirA` is degrees clockwise from the line the player faces.
  const dirA = o.dirA != null ? aim + o.dirA * D2R : cfg.dirA(aim);
  const elev = o.elev != null ? o.elev : (cfg.elev == null ? 0.08 : cfg.elev);
  const tanHalf = Math.tan(fov * 0.5 * D2R);
  const viewDir = new THREE_.Vector3(Math.sin(dirA), elev, Math.cos(dirA)).normalize();
  const place = (target, d) => {
    cam.position.copy(target).addScaledVector(viewDir, d);
    cam.lookAt(target);
    cam.updateMatrixWorld(true);
  };
  place(ctr, (sph.radius / tanHalf) * (o.margin || 1.1));
  diag.box = [
    +(box.max.x - box.min.x).toFixed(2),
    +(box.max.y - box.min.y).toFixed(2),
    +(box.max.z - box.min.z).toFixed(2),
  ];
  diag.rad = +sph.radius.toFixed(2);
  diag.camDist = +cam.position.distanceTo(ctr).toFixed(2);
  // The depth band: the pose's own bounding box, read in CAMERA space, so white-to-gray always
  // spans exactly the body in hand — and re-read after every camera move, because the band is a
  // slice of VIEW depth and moving the camera changes which slice of the body meets it.
  const band = () => {
    const inv = cam.matrixWorldInverse;
    let near = Infinity;
    let far = -Infinity;
    for (let i = 0; i < 8; i++) {
      const v = new THREE_.Vector3(
        i & 1 ? box.max.x : box.min.x,
        i & 2 ? box.max.y : box.min.y,
        i & 4 ? box.max.z : box.min.z
      ).applyMatrix4(inv);
      if (-v.z < near) near = -v.z;
      if (-v.z > far) far = -v.z;
    }
    return { near, far };
  };

  const keep = {
    res: shared.uResolution.value.clone(),
    snap: shared.uSnap.value,
    fog: shared.uFogMix.value,
    aff: shared.uAffine.value,
    ol: shared.uOutline.value,
    olt: shared.uOutlineThin.value,
    outline: settings.outline,
  };
  setOutlineEnabled(true);
  shared.uSnap.value = 0;        // a still icon does not want the wobble
  shared.uFogMix.value = 0;      // ...nor the haze: it would tint the gray ramp
  shared.uAffine.value = 0;
  // `{flat:false}` is the DEBUG view — the same frame through the ordinary materials, which is how
  // the staging and the camera angle are checked without the cut-out hiding what the body is doing.
  shared.uFlat.value = o.flat === false ? 0 : 1;
  // The gray band spans the pose's OWN depth, so the ramp means the same thing whatever the pose is
  // and however close the camera ended up. A fixed slice of depth was tried first and is wrong at
  // both ends: too long and a body only reaches partway to gray, too short and limbs that are barely
  // behind the front go fully gray. `o.ramp` scales the band (1 = the whole pose); the white-to-gray
  // curve inside it lives in the shader (see the icon mode in ps1.js).
  const rampScale = o.ramp == null ? 1 : o.ramp;
  const setBand = () => {
    const bd = band();
    shared.uFlatNear.value = bd.near;
    shared.uFlatFar.value = bd.near + Math.max(0.08, (bd.far - bd.near) * rampScale);
  };

  const rend = g.renderer;
  const rt = new THREE_.WebGLRenderTarget(64, 64, {
    minFilter: THREE_.NearestFilter,
    magFilter: THREE_.NearestFilter,
    depthBuffer: true,
    stencilBuffer: false,
    type: THREE_.UnsignedByteType,
  });
  rt.texture.colorSpace = THREE_.NoColorSpace;
  const prevClear = new THREE_.Color();
  rend.getClearColor(prevClear);
  const prevAlpha = rend.getClearAlpha();
  // One frame off the rig at `res`, with the ink `inkPx` buffer pixels wide. The target is RESIZED
  // rather than remade, because the frame is taken twice (see the first look below) and a second
  // texture allocation per icon is waste.
  const shoot = (res, inkPx) => {
    rt.setSize(res, res);
    shared.uResolution.value.set(res, res);
    shared.uOutline.value = inkPx;
    shared.uOutlineThin.value = inkPx * 0.6;
    rend.setRenderTarget(rt);
    rend.setClearColor(0xff00ff, 1);
    rend.clear();
    rend.render(iconScene, cam);
    const px = new Uint8Array(res * res * 4);
    rend.readRenderTargetPixels(rt, 0, 0, res, res, px);
    return px;
  };
  const ink = o.ink || Math.max(2, Math.round(size * 0.022));

  // ---- 4. THE FIRST LOOK, AND THE CAMERA THAT FITS IT.
  //
  // The standoff above is the sphere fit: it puts the sphere AROUND the box inside the view, and a
  // body is not a sphere. A flying knee is a long thing lying at an angle, so its box is a far
  // bigger ball than the man in it, and the first draft photographed a body filling half the buffer
  // with the crop then magnifying it (and the ink with it) by 1.7. So the frame is taken twice:
  // this cheap one, at the probe size, only to find WHERE the body actually lands in pixels — and
  // then the camera is swung to look straight at the middle of that and pulled in until the body
  // fills a fixed fraction of the buffer. The second frame is then the real one, at full size and
  // with the ink at its true thickness, because nothing magnifies it afterwards.
  setBand();
  const probe = Math.min(size, 160);
  const fill = o.fill || 0.86;
  // THREE PASSES, not one, and the reason is perspective. A single correction assumes the body's size
  // on screen scales as 1/distance, which is only true for something flat facing the lens; pulling the
  // camera in also changes the perspective, so the parts nearest it grow faster than the fit predicted.
  // The scissor and the launch both end up with the camera well under 2.5 units away and both overshot
  // far enough to run off the edge of the buffer — clipping the very limbs the icon exists to show.
  // Each pass measures the frame it actually got, so the correction is right whatever the perspective
  // did, and it stops as soon as the fit is inside half a percent.
  let passes = 0;
  for (; passes < 5; passes++) {
    const pb = pixelBounds(shoot(probe, 0), probe);
    if (!pb) break;
    const want = size * fill;
    const k = Math.min(want / (pb.w * (size / probe)), want / (pb.h * (size / probe)));
    if (passes > 0 && Math.abs(1 - k) < 0.005) break;
    const ndcX = (((pb.minX + pb.maxX + 1) / 2) / probe) * 2 - 1;
    const ndcY = 1 - (((pb.minY + pb.maxY + 1) / 2) / probe) * 2;
    const dCtr = cam.position.distanceTo(ctr);
    const tgt = cam.localToWorld(
      new THREE_.Vector3(ndcX * tanHalf * dCtr, ndcY * tanHalf * dCtr, -dCtr)
    );
    place(tgt, dCtr / k);
    diag.aim = [+ndcX.toFixed(3), +ndcY.toFixed(3), +k.toFixed(2)];
  }
  diag.passes = passes;
  setBand();
  const buf = shoot(size, ink);
  diag.camDist = +cam.position.distanceTo(ctr).toFixed(2);
  rend.setRenderTarget(null);
  rend.setClearColor(prevClear, prevAlpha);

  // ---- 4. PUT IT ALL BACK, before anything can see it (the flat mode is global).
  shared.uFlat.value = 0;
  shared.uSnap.value = keep.snap;
  shared.uFogMix.value = keep.fog;
  shared.uAffine.value = keep.aff;
  shared.uOutline.value = keep.ol;
  shared.uOutlineThin.value = keep.olt;
  setOutlineEnabled(keep.outline > 0);
  parent.add(pl.group);
  for (const [o2, v] of touched) o2.visible = v;
  g.pres.resize();               // re-writes uResolution and the ink widths from the real buffer
  rt.dispose();

  // ---- 5. THE MASK, THE CROP AND THE FIT.
  const cv = document.createElement("canvas");
  cv.width = size;
  cv.height = size;
  const cx = cv.getContext("2d");
  const img = cx.createImageData(size, size);
  let minX = size;
  let minY = size;
  let maxX = -1;
  let maxY = -1;
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const si = ((size - 1 - y) * size + x) * 4;   // WebGL hands the rows back bottom-up
      const r = buf[si];
      const gg = buf[si + 1];
      const b = buf[si + 2];
      const di = (y * size + x) * 4;
      // The key. Saturated magenta is nowhere in a white/gray/black body, so this is exact.
      const key = r > 190 && gg < 70 && b > 190;
      img.data[di] = r;
      img.data[di + 1] = gg;
      img.data[di + 2] = b;
      img.data[di + 3] = key ? 0 : 255;
      if (!key) {
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
        if (y < minY) minY = y;
        if (y > maxY) maxY = y;
      }
    }
  }
  diag.bbox = [minX, minY, maxX, maxY];
  if (maxX < 0) return { error: "nothing drawn", diag };
  cx.putImageData(img, 0, 0);
  const bw = maxX - minX + 1;
  const bh = maxY - minY + 1;
  // The fit leaves a margin around the body, and it is a proportion rather than a couple of pixels
  // because the icon is not shown at the size it is baked: 8% of 144 is 11px, which is about 3px at
  // the 34px the buttons actually draw it, and it is what stops the far boot from looking sheared off
  // at the edge of its button.
  const pad = Math.round(icon * 0.08);
  const fit = Math.min((icon - pad * 2) / bw, (icon - pad * 2) / bh);
  const oc = document.createElement("canvas");
  oc.width = icon;
  oc.height = icon;
  const ox = oc.getContext("2d");
  ox.imageSmoothingEnabled = true;
  const dw = bw * fit;
  const dh = bh * fit;
  ox.drawImage(cv, minX, minY, bw, bh, (icon - dw) / 2, (icon - dh) / 2, dw, dh);
  diag.drawn = [bw, bh, +fit.toFixed(3)];
  return { url: oc.toDataURL("image/png"), diag };
}
